apiVersion: v1
kind: ConfigMap
metadata:
  name: greetings-service
data:
  GREETINGS_MESSAGE: "Hello World From Config Map!"
  GREETINGs_NUMBER: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: greetings-service-service
spec:
  selector:
    app: greetings-service
  ports:
  - name: greetings-service-service-port
    protocol: TCP
    port: 3456
    targetPort: 5432
    nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-service-deployment
  labels:
    app: greetings-service
    version: v1
  annotations:
    prometheus.io/port: 9216
    prometheus.io/scrape: true
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetings-service
  template:
    metadata:
      labels:
        app: greetings-service
    spec:
      containers:
      - name: greetings-service
        image: greetings-service:0.0.3
        envFrom:
        - configMapRef:
            name: greetings-service
        livenessProbe:
          httpGet:
            path: /live
            port: 5432
        readinessProbe:
          httpGet:
            path: /ready
            port: 5432
        lifecycle:
          postStart:
            httpGet:
              path: /postStart
              port: 5432          
          preStop:
            httpGet:
              path: /preStop
              port: 5432          
